### ISSUE TITLE
When request urls include query parameters, the Eureka appended ones break

### ISSUE THREAD

**Issue by Mark-H** [jpdevries/eureka#11]
`/assets/components/redactor/connector.php?action=media/directories&HTTP_MODAUTH=foobar&resource=42?s=2&headers=%5Bobject%20Object%5D`

Note the question mark after &resource=42 that should be an amp

Also the headers option is being passed as `[object Object]` into the url?

**Comment by jpdevries** [comment]
> Also the headers option is being passed as [object Object] into the url?
whoops. that wasn't intended. 

@Mark-H i think i got it corrected now (fixed ? bug and removed `headers`) but one thing i noticed is HTTP_MODAUTH is being passed both through URL params and headers. Does it need to be both? Could we do just headers?
