### ISSUE TITLE
Too many (duplicate/preload) AJAX requests on render

### ISSUE THREAD

**Issue by Mark-H** [jpdevries/eureka#12]
It looks like Eureka is firing off all of these requests when rendering the browser:

- List media sources
- List files in `s=2` (nothing is selected, but I'm guessing it grabs the first media source here) for `dir=undefined` => should be set to / instead of undefined, otherwise that's good
- List directories in `s=undefined` (this one's weird)
- List directories in `s=2` (first media source - this is good)
- List directories in `s=3` (this one's weird, I don't think it should try to preload for non-selected media sources on render)
- List directories in `s=1` (another one that I don't think is needed)
- List files in `s=2` and `dir=undefined` again

It seems to me that it should be possible to bring that back to just this:
- List media sources
- List directories in `s=2` where 2 is the first media source in the list
- List files in `s=2` and `dir=/`

**Comment by jpdevries** [comment]
The `undefined` stuff should be fixed soon in the next commit. Here's the requests Eureka makes off the bat, which totals (2 + (numMediaSources * 1))

#### List Sources
Retrieves a list of all media source names and their corresponding unique identifier 
```json
{"results":[{"id":0,"name":"Filesystem"},{"id":1,"name":"Assets"},{"id":2,"name":"Amazon S3"}]}
```

#### List Directory
Lists the contents of a given directory of a given media source
```json
{"total":5,"cd":"assets\/images\/","cs":"1","results":[{"filename":"DSC02434.jpg","src":"http:\/\/jpdevries.s3.amazonaws.com\/mediabrowser\/assets\/images\/DSC02434.jpg","filesize":"1024","dimensions":"600x600","editedon":"1353215040"},{"filename":"DSC02436.jpg","src":"http:\/\/jpdevries.s3.amazonaws.com\/mediabrowser\/assets\/images\/DSC02436.jpg","filesize":"1024","dimensions":"600x600","editedon":"1353215040"},{"filename":"DSC02472.jpg","src":"http:\/\/jpdevries.s3.amazonaws.com\/mediabrowser\/assets\/images\/DSC02472.jpg","filesize":"1024","dimensions":"600x600","editedon":"1353215040"},{"filename":"DSC02487.jpg","src":"http:\/\/jpdevries.s3.amazonaws.com\/mediabrowser\/assets\/images\/DSC02487.jpg","filesize":"1024","dimensions":"600x600","editedon":"1353215040"},{"filename":"DSC02472.jpg","src":"http:\/\/jpdevries.s3.amazonaws.com\/mediabrowser\/assets\/images\/DSC02472.jpg","filesize":"1024","dimensions":"600x600","editedon":"1353215040"}]}
```

### List Source
Lists the subfolders of a given media source (1 request per media source)
```json
{"cs":"1","title":"Assets","results":[{"path":"assets","children":[{"path":"assets\/images\/"}]},{"path":"uploads"}]}
```

**Comment by jpdevries** [comment]
> List directories in s=2 where 2 is the first media source in the list

This isn't enough because the `select` lists __all__ media sources and sub folders ![](http://j4p.us/image/1c0M2V3P2s0y/Screen%20Shot%202015-05-15%20at%204.13.58%20PM.png)

could maybe support `ttl` and `localStorage` for optimization though
