### ISSUE TITLE
Various console.log statements when browsing

### ISSUE THREAD

**Issue by Mark-H** [jpdevries/eureka#39]
Reported in support ticket 6009

**Comment by jpdevries** [comment]
I think these have all since been removed



—

**Comment by Mark-H** [comment]
Hmm I am seeing a ton of them in latest redactor develop... maybe I have debug enabled somewhere, though in the eureka instantiation debug is set to false.. was there another setting for that?

**Comment by jpdevries** [comment]
Is debug turned on in lib/eureka.js?



—
